import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
	title: "Lux Works",
	description: "Generated by create next app",
	icons: "/LuxWorksLogo.png",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<script
					async
					src="https://www.googletagmanager.com/gtag/js?id=G-6LMQRS2HW5"
				></script>
				<script
					dangerouslySetInnerHTML={{
						__html: `
  window.dataLayer = window.dataLayer || [];
  function gtag(){window.dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-6LMQRS2HW5');
`,
					}}
				/>
			</head>
			<body>
				<Header />
				<main className="min-h-screen max-w-[1200px] mx-auto pt-32 px-4 md:px-6">
					{children}
					<SpeedInsights />
				</main>
				<Footer />
			</body>
		</html>
	);
}
